### ISSUE TITLE
Are these errors?

### ISSUE THREAD

**Issue by jfabernathy** [garybuhrmaster/mythhdhrrecorder#1]
Since this log entry in syslog has an "E" instead of an "I" or "C" I was wondering if it's normal or an error. I see them at the start of programs and occasionally that program will have 2 entries in the list of recordings; one in blue with no file, then one in white starting a minute late. Somethings that recording terminates earlier than scheduled. 
 
Jan 23 21:00:14 mythbuntu mythbackend[2450]: mythbackend[2450]: E ExternSH recorders/dtvsignalmonitor.cpp:323 (HandlePAT) DTVSigMon[1](/usr/local/bin/mythhdhrrecorder --hdhr 1074C841
                                             Program Association Section
                                              PSIP tableID(0x0) length(13) extension(0x701)
                                                   version(0) current(1) section(0) last_section(0)
                                                   tsid(1793) programCount(1)
                                               program number     3 has PID 0x0030

**Comment by garybuhrmaster** [comment]
These HandlePAT messages are typically an artifact of how the current MythTV recorder handles streams, expecting a full set of program descriptor tables (used to decode the transport stream), which will usually not be fully available with external streams (one has seen them from day one with the HDHR (and I think the Ceton) when using CableCARDs, since those devices have to deal with the CableCARD OCUR adjustments).  The messages should probably be more warnings than errors for these use cases, but since they were very unusual before OCUR and External Recorders, I doubt any dev cares to add sufficient state on the recorder instance to reduce the levels for those specific types of recorders (you are, of course, free to submit such a patch).

**Comment by garybuhrmaster** [comment]
btw, if you are getting an empty recording, that may be something different.  You should make sure you are using the latest mythhdhrrecorder, and also the latest fixes/30.  In particular, there *were* some specific fixes added late in the v30 development cycle that addressed certain issues with timeouts and other issues with external recorders (John found/fixed a number of edge cases, but of course an edge case for him may be something more common for you).  I am not sure the project has formally announced the v30 release, but it is out there.  If you are using the latest versions and you have a reproducer, you should probably add in sufficient debug logging and create a ticket to see if some dev can identify the cause.

**Comment by jfabernathy** [comment]
Okay, I'm on the latest v29.1 and want to switch to v30. In fact I built v30 on archlinux, but my production mythtv is on ubuntu server 18.04 LTS.  with everything backed up, do I just change the PPA and update???

**Comment by garybuhrmaster** [comment]
No idea if there is a PPA.  You could ask the people who build them.
